// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABNhgnt93_5UbuDuGyAScMkD_kGhtwKF4',
    appId: '1:371165846267:web:a50f090baa8818f3d1ae5e',
    messagingSenderId: '371165846267',
    projectId: 'processorder-f7a3c',
    authDomain: 'processorder-f7a3c.firebaseapp.com',
    storageBucket: 'processorder-f7a3c.firebasestorage.app',
    measurementId: 'G-32TCR45534',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnwx6RQqUphBpI8cDjvYifWCHme5GQf8',
    appId: '1:371165846267:android:c0036b6ef8f1d79cd1ae5e',
    messagingSenderId: '371165846267',
    projectId: 'processorder-f7a3c',
    storageBucket: 'processorder-f7a3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsrZotY9a-OWdOcyfoeyP0Wsv7jaoTxWg',
    appId: '1:371165846267:ios:b3bc9a634d558e69d1ae5e',
    messagingSenderId: '371165846267',
    projectId: 'processorder-f7a3c',
    storageBucket: 'processorder-f7a3c.firebasestorage.app',
    iosBundleId: 'com.example.processOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsrZotY9a-OWdOcyfoeyP0Wsv7jaoTxWg',
    appId: '1:371165846267:ios:b3bc9a634d558e69d1ae5e',
    messagingSenderId: '371165846267',
    projectId: 'processorder-f7a3c',
    storageBucket: 'processorder-f7a3c.firebasestorage.app',
    iosBundleId: 'com.example.processOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABNhgnt93_5UbuDuGyAScMkD_kGhtwKF4',
    appId: '1:371165846267:web:9fd5c382d8f74122d1ae5e',
    messagingSenderId: '371165846267',
    projectId: 'processorder-f7a3c',
    authDomain: 'processorder-f7a3c.firebaseapp.com',
    storageBucket: 'processorder-f7a3c.firebasestorage.app',
    measurementId: 'G-S5MMQDZPLQ',
  );
}
